### ISSUE TITLE
`Could not pull latest version information: SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON` in the action output

### ISSUE THREAD

**Issue by kkovaletp** [codecov/test-results-action#103]
I run this action in the scope of CI workflow in the public repo (both in `master` and in PRs from a forked repo).
Here is the action definitions:
- API job:
```yml
    - name: Upload test execution results
      uses: codecov/test-results-action@v1.0.1
      if: ${{ steps.test.conclusion == 'success' || steps.test.conclusion == 'failure' }}
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        flags: api-${{ matrix.database }}
        files: ./api/test-api-coverage-report.xml
```
- UI job:
```yml
    - name: Upload test execution results
      uses: codecov/test-results-action@v1.0.1
      if: ${{ steps.test.conclusion == 'success' || steps.test.conclusion == 'failure' }}
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        flags: ui
        directory: ./ui
```

Every time I look into the action output, I see the next error:
```
==> Running version latest
Could not pull latest version information: SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON
```

Here are the execution examples:
- `master` branch: https://github.com/photoview/photoview/actions/runs/12200416188/job/34036516921#step:8:25
- a PR from a forked repo: https://github.com/photoview/photoview/actions/runs/12211556848/job/34068982224?pr=1139#step:7:25
