### ISSUE TITLE
[BUG] Not detecting reports even though they contain `junit` in the name

### ISSUE THREAD

**Issue by joseph-sentry** [codecov/test-results-action#110]
In this [PR](https://github.com/getsentry/sentry-javascript/pull/15341), it was necessary to specify the files using a glob pattern to detect the files for the browser unit tests. [before](https://github.com/getsentry/sentry-javascript/actions/runs/13205016068/job/36866344997?pr=15341)  [after](https://github.com/getsentry/sentry-javascript/actions/runs/13207000168/job/36874091470?pr=15341)

since those files contain `junit` in the name, they should be automatically detected, so something is wrong with the detection in the CLI, it's possible that it's incapable of detecting reports nested in deeper directories.

**Comment by dvins** [comment]
Ditto. I'm several hours in and discovering the same issue when using with a monorepo, we even make it easy and pre-gather all the results int a single folder, and it's still not working. Ridiculous.

**Comment by dvins** [comment]
Through some shell magic I was able to rejigger our GitHub Workflow and get this to work.

My monorepo test workflow already gathers all the relevant test coverage and result files from each of our projects into a single location, namely so we can merge coverage. I ultimately added a step to enumerate the list of _junit.xml_ files into a variable, and then explicitly pass that list into the Codecov Test Results action via the `files` attribute:

```yaml
steps:
  - name: Collect Test Coverage & Results
    run: |
      pnpm turbo coverage:gather
      pnpm turbo coverage:merge
      pnpm turbo coverage:report
  
  - name: "Generate Test Results File List (See: https://github.com/codecov/test-results-action/issues/110)"
    id: test-results
    run: |
      FILES=$(find ./coverage/raw/junit -type f -name "*.junit.xml" | paste -sd "," -)
      echo "file_list=$FILES" >> $GITHUB_OUTPUT
      echo "file_list=$FILES"
  
  - name: Upload Test Results to Sentry Codecov
    if: ${{ !cancelled() }}
    uses: codecov/test-results-action@v1
    timeout-minutes: 10
    with:
      directory: coverage/raw/junit
      files: ${{ steps.test-results.outputs.file_list }}
      flags: unit
      token: ${{ secrets.CODECOV_TOKEN }}
```

Note I still had to add the `directory` attribute, because otherwise the Codecov Test Results action still scavenges files from everywhere else, so you end up with duplicates.

Even better, the action when it executes emits a cryptic warning in the logs, "Some files being explicitly added are found in the list of excluded files for upload. We are still going to search for the explicitly added files." Makes. No. Sense.

Anyhow, after all this effort, have to say, the Tests tab in the Codecov UI is quite underwhelming. It doesn't even rollup by test suite let alone module and folder!
